---
version: "2.1"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest #26mb
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Asia/Bangkok
      - SUBDOMAINS=subdomain1,subdomain2
      - TOKEN=token
      - LOG_FILE=false #optional
    #volumes:
      #- /path/to/appdata/config:/config #optional
    restart: unless-stopped
